version: "3"

services:
  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo
    volumes:
      - "db_data:/var/lib/postgresql/data"

  web:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env.dev

volumes:
  db_data:
